### PR TITLE
Add more registration info

### PR DESCRIPTION
**Pull request by di**
- Information about which ticket to buy
- What's included in the ticket price
- etc.

### CODE REVIEW

**Review by pizzapanther — COMMENTED** [review]
i was wondering if we consider bootcampers students and if so add that? I would say yes.

**Comment by di** [comment]
@pizzapanther How bout I just drop the "of academic institutions" part?

**Comment by pizzapanther** [comment]
sure

**Comment by pizzapanther** [comment]
Deployed

**Pull request merged**
